# Use a Node.js base image
FROM node:20

# Set the working directory
WORKDIR /app/server

# Copy package.json and package-lock.json
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY server/ .

# Expose a port if needed (e.g., if your backend runs on a specific port)
EXPOSE 8800

# Start the backend server
CMD ["node", "index.js"]
